import BaseSeeder from '@ioc:Adonis/Lucid/Seeder'
import FilasColumnas from 'App/Infraestructura/Datos/Entidad/FilasColumnas'


export default class extends BaseSeeder {
  public async run() {
    await FilasColumnas.createMany([
      {id: 1, filaClasificacionId: 1, columnaClasificacionId: 1 },
      {id: 2, filaClasificacionId: 2, columnaClasificacionId: 1 },
      {id: 3, filaClasificacionId: 3, columnaClasificacionId: 1 },
      {id: 4, filaClasificacionId: 4, columnaClasificacionId: 1 },
      {id: 5, filaClasificacionId: 5, columnaClasificacionId: 1 },
      {id: 6, filaClasificacionId: 6, columnaClasificacionId: 2 },
      {id: 7, filaClasificacionId: 7, columnaClasificacionId: 2 },
      {id: 8, filaClasificacionId: 8, columnaClasificacionId: 2 },
      {id: 9, filaClasificacionId: 9, columnaClasificacionId: 2 },
      {id: 10, filaClasificacionId: 10, columnaClasificacionId: 2 },
      {id: 11, filaClasificacionId: 11, columnaClasificacionId: 2 },
      {id: 12, filaClasificacionId: 6, columnaClasificacionId: 3 },
      {id: 13, filaClasificacionId: 7, columnaClasificacionId: 3 },
      {id: 14, filaClasificacionId: 8, columnaClasificacionId: 3 },
      {id: 15, filaClasificacionId: 9, columnaClasificacionId: 3 },
      {id: 16, filaClasificacionId: 10, columnaClasificacionId: 3 },
      {id: 17, filaClasificacionId: 11, columnaClasificacionId: 3 },
      {id: 18, filaClasificacionId: 6, columnaClasificacionId: 4 },
      {id: 19, filaClasificacionId: 7, columnaClasificacionId: 4 },
      {id: 20, filaClasificacionId: 8, columnaClasificacionId: 4 },
      {id: 21, filaClasificacionId: 9, columnaClasificacionId: 4 },
      {id: 22, filaClasificacionId: 10, columnaClasificacionId: 4 },
      {id: 23, filaClasificacionId: 11, columnaClasificacionId: 4 },
      {id: 24, filaClasificacionId: 6, columnaClasificacionId: 5 },
      {id: 25, filaClasificacionId: 7, columnaClasificacionId: 5 },
      {id: 26, filaClasificacionId: 8, columnaClasificacionId: 5 },
      {id: 27, filaClasificacionId: 9, columnaClasificacionId: 5 },
      {id: 28, filaClasificacionId: 10, columnaClasificacionId: 5 },
      {id: 29, filaClasificacionId: 11, columnaClasificacionId: 5 },
      {id: 30, filaClasificacionId: 6, columnaClasificacionId: 6 },
      {id: 31, filaClasificacionId: 7, columnaClasificacionId: 6 },
      {id: 32, filaClasificacionId: 8, columnaClasificacionId: 6 },
      {id: 33, filaClasificacionId: 9, columnaClasificacionId: 6 },
      {id: 34, filaClasificacionId: 10, columnaClasificacionId: 6 },
      {id: 35, filaClasificacionId: 11, columnaClasificacionId: 6 },
      {id: 36, filaClasificacionId: 6, columnaClasificacionId: 7 },
      {id: 37, filaClasificacionId: 7, columnaClasificacionId: 7 },
      {id: 38, filaClasificacionId: 8, columnaClasificacionId: 7 },
      {id: 39, filaClasificacionId: 9, columnaClasificacionId: 7 },
      {id: 40, filaClasificacionId: 10, columnaClasificacionId: 7 },
      {id: 41, filaClasificacionId: 11, columnaClasificacionId: 7 },
      {id: 42, filaClasificacionId: 12, columnaClasificacionId: 8 },
      {id: 43, filaClasificacionId: 13, columnaClasificacionId: 8 },
      {id: 44, filaClasificacionId: 14, columnaClasificacionId: 8 },
      {id: 45, filaClasificacionId: 15, columnaClasificacionId: 8 },
      {id: 46, filaClasificacionId: 16, columnaClasificacionId: 8 },
      {id: 47, filaClasificacionId: 17, columnaClasificacionId: 8 },
      {id: 48, filaClasificacionId: 18, columnaClasificacionId: 8 },
      {id: 49, filaClasificacionId: 19, columnaClasificacionId: 8 },
      {id: 50, filaClasificacionId: 12, columnaClasificacionId: 9 },
      {id: 51, filaClasificacionId: 13, columnaClasificacionId: 9 },
      {id: 52, filaClasificacionId: 14, columnaClasificacionId: 9 },
      {id: 53, filaClasificacionId: 15, columnaClasificacionId: 9 },
      {id: 54, filaClasificacionId: 16, columnaClasificacionId: 9 },
      {id: 55, filaClasificacionId: 17, columnaClasificacionId: 9 },
      {id: 56, filaClasificacionId: 18, columnaClasificacionId: 9 },
      {id: 57, filaClasificacionId: 19, columnaClasificacionId: 9 },
      {id: 58, filaClasificacionId: 20, columnaClasificacionId: 10 },
      {id: 59, filaClasificacionId: 21, columnaClasificacionId: 10 },
      {id: 60, filaClasificacionId: 22, columnaClasificacionId: 10 },
      {id: 61, filaClasificacionId: 23, columnaClasificacionId: 10 },
      {id: 62, filaClasificacionId: 24, columnaClasificacionId: 10 },
      {id: 63, filaClasificacionId: 25, columnaClasificacionId: 10 },
      {id: 64, filaClasificacionId: 26, columnaClasificacionId: 10 },
      {id: 65, filaClasificacionId: 27, columnaClasificacionId: 10 },
      {id: 66, filaClasificacionId: 28, columnaClasificacionId: 10 },
      {id: 67, filaClasificacionId: 29, columnaClasificacionId: 10 },
      {id: 68, filaClasificacionId: 30, columnaClasificacionId: 10 },
      {id: 69, filaClasificacionId: 31, columnaClasificacionId: 10 },
      {id: 70, filaClasificacionId: 32, columnaClasificacionId: 10 },
      {id: 71, filaClasificacionId: 20, columnaClasificacionId: 11 },
      {id: 72, filaClasificacionId: 21, columnaClasificacionId: 11 },
      {id: 73, filaClasificacionId: 22, columnaClasificacionId: 11 },
      {id: 74, filaClasificacionId: 23, columnaClasificacionId: 11 },
      {id: 75, filaClasificacionId: 24, columnaClasificacionId: 11 },
      {id: 76, filaClasificacionId: 25, columnaClasificacionId: 11 },
      {id: 77, filaClasificacionId: 26, columnaClasificacionId: 11 },
      {id: 78, filaClasificacionId: 27, columnaClasificacionId: 11 },
      {id: 79, filaClasificacionId: 28, columnaClasificacionId: 11 },
      {id: 80, filaClasificacionId: 29, columnaClasificacionId: 11 },
      {id: 81, filaClasificacionId: 30, columnaClasificacionId: 11 },
      {id: 82, filaClasificacionId: 31, columnaClasificacionId: 11 },
      {id: 83, filaClasificacionId: 32, columnaClasificacionId: 11 },
      {id: 84, filaClasificacionId: 20, columnaClasificacionId: 12 },
      {id: 85, filaClasificacionId: 21, columnaClasificacionId: 12 },
      {id: 86, filaClasificacionId: 22, columnaClasificacionId: 12 },
      {id: 87, filaClasificacionId: 23, columnaClasificacionId: 12 },
      {id: 88, filaClasificacionId: 24, columnaClasificacionId: 12 },
      {id: 89, filaClasificacionId: 25, columnaClasificacionId: 12 },
      {id: 90, filaClasificacionId: 26, columnaClasificacionId: 12 },
      {id: 91, filaClasificacionId: 27, columnaClasificacionId: 12 },
      {id: 92, filaClasificacionId: 28, columnaClasificacionId: 12 },
      {id: 93, filaClasificacionId: 29, columnaClasificacionId: 12 },
      {id: 94, filaClasificacionId: 30, columnaClasificacionId: 12 },
      {id: 95, filaClasificacionId: 31, columnaClasificacionId: 12 },
      {id: 96, filaClasificacionId: 32, columnaClasificacionId: 12 }

    ])
  }
}
