import BaseSeeder from '@ioc:Adonis/Lucid/Seeder'
import ClasificacionClasificaciones from 'App/Infraestructura/Datos/Entidad/ClasificacionClasificaciones'


export default class extends BaseSeeder {
  public async run() {
    await ClasificacionClasificaciones.createMany([
      {clasificacionId:	1	,clasificacionesId:	1	},
{clasificacionId:	3	,clasificacionesId:	1	},
{clasificacionId:	4	,clasificacionesId:	1	},
{clasificacionId:	5	,clasificacionesId:	1	},
{clasificacionId:	6	,clasificacionesId:	1	},
{clasificacionId:	7	,clasificacionesId:	1	},
{clasificacionId:	8	,clasificacionesId:	1	},
{clasificacionId:	9	,clasificacionesId:	1	},
{clasificacionId:	10	,clasificacionesId:	1	},
{clasificacionId:	12	,clasificacionesId:	1	},
{clasificacionId:	14	,clasificacionesId:	1	},
{clasificacionId:	15	,clasificacionesId:	1	},
{clasificacionId:	16	,clasificacionesId:	1	},
{clasificacionId:	17	,clasificacionesId:	1	},
{clasificacionId:	20	,clasificacionesId:	1	},
{clasificacionId:	22	,clasificacionesId:	1	},
{clasificacionId:	23	,clasificacionesId:	1	},
{clasificacionId:	24	,clasificacionesId:	1	},
{clasificacionId:	1	,clasificacionesId:	2	},
{clasificacionId:	2	,clasificacionesId:	2	},
{clasificacionId:	3	,clasificacionesId:	2	},
{clasificacionId:	4	,clasificacionesId:	2	},
{clasificacionId:	5	,clasificacionesId:	2	},
{clasificacionId:	6	,clasificacionesId:	2	},
{clasificacionId:	7	,clasificacionesId:	2	},
{clasificacionId:	8	,clasificacionesId:	2	},
{clasificacionId:	9	,clasificacionesId:	2	},
{clasificacionId:	10	,clasificacionesId:	2	},
{clasificacionId:	12	,clasificacionesId:	2	},
{clasificacionId:	13	,clasificacionesId:	2	},
{clasificacionId:	14	,clasificacionesId:	2	},
{clasificacionId:	15	,clasificacionesId:	2	},
{clasificacionId:	16	,clasificacionesId:	2	},
{clasificacionId:	17	,clasificacionesId:	2	},
{clasificacionId:	18	,clasificacionesId:	2	},
{clasificacionId:	19	,clasificacionesId:	2	},
{clasificacionId:	20	,clasificacionesId:	2	},
{clasificacionId:	22	,clasificacionesId:	2	},
{clasificacionId:	23	,clasificacionesId:	2	},
{clasificacionId:	24	,clasificacionesId:	2	},
{clasificacionId:	1	,clasificacionesId:	3	},
{clasificacionId:	2	,clasificacionesId:	3	},
{clasificacionId:	3	,clasificacionesId:	3	},
{clasificacionId:	4	,clasificacionesId:	3	},
{clasificacionId:	5	,clasificacionesId:	3	},
{clasificacionId:	6	,clasificacionesId:	3	},
{clasificacionId:	7	,clasificacionesId:	3	},
{clasificacionId:	8	,clasificacionesId:	3	},
{clasificacionId:	9	,clasificacionesId:	3	},
{clasificacionId:	10	,clasificacionesId:	3	},
{clasificacionId:	11	,clasificacionesId:	3	},
{clasificacionId:	12	,clasificacionesId:	3	},
{clasificacionId:	13	,clasificacionesId:	3	},
{clasificacionId:	14	,clasificacionesId:	3	},
{clasificacionId:	15	,clasificacionesId:	3	},
{clasificacionId:	16	,clasificacionesId:	3	},
{clasificacionId:	17	,clasificacionesId:	3	},
{clasificacionId:	18	,clasificacionesId:	3	},
{clasificacionId:	19	,clasificacionesId:	3	},
{clasificacionId:	20	,clasificacionesId:	3	},
{clasificacionId:	21	,clasificacionesId:	3	},
{clasificacionId:	22	,clasificacionesId:	3	},
{clasificacionId:	23	,clasificacionesId:	3	},
{clasificacionId:	24	,clasificacionesId:	3	}

    ])
  }
}
